### PR TITLE
Refactor plugin generator

### PR DESCRIPTION
**Pull request by hariadi**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
this is great! thanks!

**Comment by hariadi** [comment]
@doowb, @jonschlinkert  if you don't mind, can you add me to npm for that two generator repo

**Comment by jonschlinkert** [comment]
of course!

**Comment by jonschlinkert** [comment]
done! please check and make sure. I wish this was done automatically for new packages, it's something I never think about. Just let me know when you need to be added to something else, thanks again!

**Comment by hariadi** [comment]
Great! Thanks.

Don't forget to add in https://npmjs.org/package/generator-plugin too. :+1:

**Comment by jonschlinkert** [comment]
no prob!

**Comment by jonschlinkert** [comment]
actually I think I did already! but check and make sure, thanks!

**Comment by hariadi** [comment]
:+1:

**Pull request merged**
