### PR TITLE
Correcting stage names to match assemble. pre/post instead of before/aft...

### PR DESCRIPTION
**Pull request by jarrodconnolly**
In assemble the stages are named using pre/post instead of before/after that the generator was using.

https://github.com/assemble/assemble/blob/45cd0338369df84923be1db08a9c4ad59bca5a72/tasks/assemble.js#L445

### CODE REVIEW

**Comment by doowb** [comment]
Hi @jarrodconnolly . This generator is intended to be used with the refactor version of assemble, which isn't completely finished yet. It's taken longer to release than we planned and the "stages" have changed quite a bit.

This was supposed to be a place holder and I thought I added that to the README, but I must have missed it. I think I might hold off on this, unless people think there could be value in having a generator that produces files for the current version of assemble, then we'll need to update the `_index.js` file in the templates to match the correct plugin signature.

**Comment by jarrodconnolly** [comment]
Sounds good, I understand whats going on now. I was just trying to use it to generate a starting point for a plugin and noticed the difference in the stage names.

Looking forward to the refactored version of assemble.

**Comment by jonschlinkert** [comment]
:+1: thanks a lot @jarrodconnolly, it's much appreciated!

**Comment by doowb** [comment]
I updated the `stages` to `events` and updated to what they'll be in `0.5.0` of assemble.

**Pull request closed without merging**
